const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TAGS=['Passer','Defender','Setter','Attacker','Blocker','Hustle'],T1=['Defender','Passer','Attacker'],T2=['Hustle','Setter','Blocker'];
let db,state={players:[],selected:[],teams:[],locks:[],history:[],settings:{courts:2,threeAdj:.25,historyDepth:3},passHash:''};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('volley-builder',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){db=await openDB();const x=await new Promise((res,rej)=>{const r=db.transaction('state').objectStore('state').get('app');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(x)state={...state,...x,settings:{...state.settings,...x.settings}};state.players=state.players.map(p=>({...p,last:p.last||'',gender:['M','F'].includes(p.gender)?p.gender:'',tags:Array.isArray(p.tags)?p.tags:[],rating:Math.min(6,Math.max(1,+p.rating||3))}));$('#courts').value=state.settings.courts;$('#threeAdj').value=state.settings.threeAdj;$('#historyDepth').value=state.settings.historyDepth;renderAll();if(state.passHash)$('#gate').classList.remove('hidden')}
function save(){return new Promise((res,rej)=>{const r=db.transaction('state','readwrite').objectStore('state').put(state,'app');r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function nm(p,full=false){const l=(p.last||'').trim();return full?(l?`${p.first} ${l}`:p.first):(l?`${p.first} ${l[0].toUpperCase()}.`:p.first)}
function playersSorted(){return [...state.players].sort((a,b)=>a.first.localeCompare(b.first)||(a.last||'').localeCompare(b.last||''))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2600)}
function tab(id){$$('.tab,nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`nav button[data-tab="${id}"]`).classList.add('active')}
function renderChecks(){$('#playerChecks').innerHTML=playersSorted().map(p=>`<label class="player-check"><input type="checkbox" data-id="${p.id}" ${state.selected.includes(p.id)?'checked':''}><span>${nm(p)}</span></label>`).join('');$('#selectedCount').textContent=state.selected.length;$('#status').textContent=`Version 1.2 • ${state.players.length} players`}
function renderTags(){if(!$('#tagInputs').children.length)$('#tagInputs').innerHTML=TAGS.map(t=>`<label class="chip"><input type="checkbox" value="${t}">${t}</label>`).join('')}
function renderRoster(){$('#rosterList').innerHTML=playersSorted().map(p=>`<div class="roster-row"><div><b>${nm(p,true)}</b><div class="meta"><span class="pill">${(+p.rating).toFixed(1)}</span>${p.gender?`<span class="pill">${p.gender}</span>`:''}${p.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div></div><button class="secondary edit" data-id="${p.id}">Edit</button><button class="danger del" data-id="${p.id}">Remove</button></div>`).join('')}
const player=id=>state.players.find(p=>p.id===id),avg=t=>t.reduce((s,id)=>s+player(id).rating,0)/t.length,hasTag=(t,x)=>t.some(id=>player(id).tags.includes(x));
function coverage(team){const coed=team.some(id=>player(id).gender==='F');return `<div class="coverage"><span class="pill ${coed?'ok':'miss'}">${coed?'✅':'❌'} Coed</span><span class="tier-label">Tier 1</span>${T1.map(t=>`<span class="pill ${hasTag(team,t)?'ok':'miss'}">${hasTag(team,t)?'✅':'❌'} ${t}</span>`).join('')}<span class="tier-label">Tier 2</span>${T2.map(t=>`<span class="pill ${hasTag(team,t)?'ok':'miss'}">${hasTag(team,t)?'✅':'❌'} ${t}</span>`).join('')}</div>`}
function renderTeams(){$('#teamGrid').innerHTML=state.teams.map((t,i)=>`<article class="team-card"><h2>Team ${i+1}<small>Avg ${avg(t).toFixed(2)}</small></h2><ul>${t.map(id=>`<li>${nm(player(id))}</li>`).join('')}</ul>${coverage(t)}<button class="lock ${state.locks[i]?'locked':''}" data-i="${i}">${state.locks[i]?'Locked':'Lock team'}</button></article>`).join('');if(state.teams.length){$('#teamNotice').textContent=`${state.teams.length} teams • ${state.locks.filter(Boolean).length} locked`;const ids=state.teams.flat(),ct=state.teams.length,c={F:ids.filter(id=>player(id).gender==='F').length};const parts=[`Coed qualifiers: ${c.F}/${ct}`,...TAGS.map(x=>`${x}: ${ids.filter(id=>player(id).tags.includes(x)).length}/${ct}`)];$('#availability').textContent=parts.join(' • ');$('#availability').classList.remove('hidden')}}
function renderAll(){renderTags();renderChecks();renderRoster();renderTeams()}
function sizesFor(n,c){let o=[];for(let t=2;t<=c*2;t+=2)if(n>=3*t&&n<=5*t){let s=Array(t).fill(Math.floor(n/t));for(let i=0;i<n%t;i++)s[i]++;if(Math.min(...s)>=3&&Math.max(...s)<=5)o.push(s)}return o.sort((a,b)=>b.length-a.length)[0]||null}
const pair=(a,b)=>[a,b].sort().join('|');function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function score(teams){const powers=teams.map(t=>avg(t)-(t.length===3?+state.settings.threeAdj:0)),mean=powers.reduce((a,b)=>a+b,0)/powers.length;let s=powers.reduce((z,v)=>z+(v-mean)**2,0)*90+(Math.max(...powers)-Math.min(...powers))*35;for(const t of teams){for(const x of T1)if(!hasTag(t,x))s+=18;for(const x of T2)if(!hasTag(t,x))s+=5}state.history.slice(0,+state.settings.historyDepth).forEach((session,h)=>{const old=new Set();session.forEach(t=>{for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++)old.add(pair(t[i],t[j]))});teams.forEach(t=>{for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++)if(old.has(pair(t[i],t[j])))s+=h===0?12:3/(h+1)})});return s+Math.random()*.05}
function optimize(ids,sizes,locked=[]){let best,bs=Infinity;for(let k=0;k<7000;k++){const pool=shuffle(ids),teams=[];let p=0;for(const z of sizes){teams.push(pool.slice(p,p+z));p+=z}const v=score([...locked,...teams]);if(v<bs){bs=v;best=teams}}return best}
function createTeams(){state.settings.courts=+$('#courts').value;const s=sizesFor(state.selected.length,state.settings.courts);if(!s)return toast(`Choose a count that makes 2–${state.settings.courts*2} teams of 3–5.`);state.teams=optimize(state.selected,s);state.locks=Array(state.teams.length).fill(false);save();renderTeams();tab('teams')}
function reshuffle(){const locked=state.teams.filter((_,i)=>state.locks[i]),u=state.teams.filter((_,i)=>!state.locks[i]);if(!u.length)return toast('Unlock at least one team.');const fresh=optimize(u.flat(),u.map(t=>t.length),locked);let q=0;state.teams=state.teams.map((t,i)=>state.locks[i]?t:fresh[q++]);save();renderTeams()}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('volley|'+s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
$$('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#playerChecks').onchange=async e=>{const id=e.target.dataset.id;if(!id)return;state.selected=e.target.checked?[...new Set([...state.selected,id])]:state.selected.filter(x=>x!==id);await save();renderChecks()};$('#selectAll').onclick=async()=>{state.selected=state.players.map(p=>p.id);await save();renderChecks()};$('#clearAll').onclick=async()=>{state.selected=[];await save();renderChecks()};$('#createTeams').onclick=createTeams;$('#reshuffle').onclick=reshuffle;$('#teamGrid').onclick=async e=>{if(!e.target.classList.contains('lock'))return;const i=+e.target.dataset.i;state.locks[i]=!state.locks[i];await save();renderTeams()};
$('#playerForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value||uid(),p={id,first:$('#firstName').value.trim(),last:$('#lastName').value.trim(),rating:+$('#rating').value,gender:$('#gender').value,tags:$$('#tagInputs input:checked').map(x=>x.value)};if(!p.first||p.rating<1||p.rating>6)return toast('Enter a first name and rating from 1.0–6.0.');const i=state.players.findIndex(x=>x.id===id);if(i>=0)state.players[i]=p;else state.players.push(p);resetForm();await save();renderAll()};
function resetForm(){$('#playerForm').reset();$('#rating').value='3.0';$('#editId').value='';$('#savePlayer').textContent='Add player';$('#cancelEdit').classList.add('hidden')}
$('#cancelEdit').onclick=resetForm;$('#rosterList').onclick=async e=>{const id=e.target.dataset.id;if(!id)return;const p=player(id);if(e.target.classList.contains('edit')){$('#firstName').value=p.first;$('#lastName').value=p.last;$('#rating').value=p.rating;$('#gender').value=p.gender;$$('#tagInputs input').forEach(x=>x.checked=p.tags.includes(x.value));$('#editId').value=id;$('#savePlayer').textContent='Save changes';$('#cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}else if(e.target.classList.contains('del')&&confirm(`Remove ${nm(p,true)}?`)){state.players=state.players.filter(x=>x.id!==id);state.selected=state.selected.filter(x=>x!==id);await save();renderAll()}};
$('#publish').onclick=async()=>{if(!state.teams.length)return toast('Create teams first.');state.history.unshift(state.teams.map(t=>[...t]));state.history=state.history.slice(0,10);await save();$('#publishedTeams').innerHTML=state.teams.map((t,i)=>`<article class="published-card"><h2>Team ${i+1}</h2><ul>${t.map(id=>`<li>${nm(player(id))}</li>`).join('')}</ul></article>`).join('');$('#publishView').classList.remove('hidden')};$('#closePublish').onclick=()=>$('#publishView').classList.add('hidden');
$('#saveSettings').onclick=async()=>{state.settings={...state.settings,courts:+$('#courts').value,threeAdj:+$('#threeAdj').value,historyDepth:+$('#historyDepth').value};await save();toast('Settings saved.')};$('#clearHistory').onclick=async()=>{if(confirm('Clear history?')){state.history=[];await save();toast('History cleared.')}};$('#setCode').onclick=async()=>{const x=$('#newCode').value;if(x.length<4)return toast('Use at least 4 characters.');state.passHash=await hash(x);await save();$('#newCode').value='';toast('Passcode set.')};$('#removeCode').onclick=async()=>{state.passHash='';await save();toast('Passcode removed.')};$('#unlockForm').onsubmit=async e=>{e.preventDefault();if(await hash($('#unlockCode').value)===state.passHash)$('#gate').classList.add('hidden');else toast('Incorrect passcode.')};
$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify({...state,passHash:''},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='volleyball-v1.2-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d.players))throw 0;const passHash=state.passHash;state={...state,...d,passHash,settings:{...state.settings,...d.settings}};state.players=state.players.map(p=>({...p,last:p.last||'',gender:['M','F'].includes(p.gender)?p.gender:'',tags:Array.isArray(p.tags)?p.tags:[]}));await save();renderAll();toast('Backup imported.')}catch{toast('Invalid backup.')}};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));load();