const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VERSION='1.5.2';
const TAGS=['Passer','Hustle','Defender','Setter','Attacker','Blocker'],T1=['Passer','Hustle','Defender'],T2=['Setter','Attacker','Blocker'];
let db,state={players:[],selected:[],teams:[],locks:[],history:[],revision:0,updatedAt:0,settings:{courts:2,threeAdj:.25},passHash:'',rosterMeta:null,filters:{name:'',ratings:[],genders:[],tags:[],tagMode:'any',special:[],sortBy:'firstAsc'}};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('volley-builder',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function defaultState(){return {players:[],selected:[],teams:[],locks:[],history:[],revision:0,updatedAt:0,settings:{courts:2,threeAdj:.25},passHash:'',rosterMeta:null,filters:{name:'',ratings:[],genders:[],tags:[],tagMode:'any',special:[],sortBy:'firstAsc'}}}
function normalizeState(raw){const base=defaultState(),x=raw&&typeof raw==='object'?raw:{};const out={...base,...x,settings:{...base.settings,...(x.settings||{})},filters:{...base.filters,...(x.filters||{})}};out.players=Array.isArray(x.players)?x.players.map((p,i)=>({...p,id:p.id||uid(),first:(p.first||'').trim(),last:p.last||'',gender:['M','F'].includes(p.gender)?p.gender:'',tags:Array.isArray(p.tags)?p.tags:[],rating:Math.min(10,Math.max(1,+p.rating||3)),createdAt:p.createdAt||Date.now()+i})).filter(p=>p.first):[];out.selected=Array.isArray(x.selected)?x.selected.filter(id=>out.players.some(p=>p.id===id)):[];out.teams=Array.isArray(x.teams)?x.teams.map(t=>Array.isArray(t)?t.filter(id=>out.players.some(p=>p.id===id)):[]):[];out.locks=Array.isArray(x.locks)?x.locks.slice(0,out.teams.length):[];while(out.locks.length<out.teams.length)out.locks.push(false);out.history=Array.isArray(x.history)?x.history.slice(-50):[];out.revision=Math.max(0,+x.revision||0);out.updatedAt=Math.max(0,+x.updatedAt||0);return out}
async function load(){db=await openDB();const stored=await new Promise((res,rej)=>{const r=db.transaction('state').objectStore('state').get('app');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});let shadow=null;try{shadow=JSON.parse(localStorage.getItem('volley-builder-shadow')||'null')}catch{}const storedRevision=Math.max(0,+stored?.revision||0),shadowRevision=Math.max(0,+shadow?.revision||0),source=!stored?shadow:!shadow?stored:shadowRevision>storedRevision?shadow:stored;state=normalizeState(source);$('#courts').value=state.settings.courts;$('#threeAdj').value=state.settings.threeAdj;restoreFilterControls();renderAll();if(state.passHash)$('#gate').classList.remove('hidden');if(state.players.length)toast(`Local roster loaded: ${state.players.length} players`);else toast('No local roster found on this device.');await save()}
function save(){state.revision=(+state.revision||0)+1;state.updatedAt=Date.now();const snapshot=JSON.stringify(state);try{localStorage.setItem('volley-builder-shadow',snapshot)}catch{}return new Promise((res,rej)=>{const r=db.transaction('state','readwrite').objectStore('state').put(state,'app');r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function nm(p,full=false){const l=String(p.last||'').trim(),f=String(p.first||'');return full?(l?`${f} ${l}`:f):(l?`${f} ${l[0].toUpperCase()}.`:f)}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function playersSorted(){return [...state.players].sort((a,b)=>a.first.localeCompare(b.first)||(a.last||'').localeCompare(b.last||''))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2600)}
function tab(id){$$('.tab,nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`nav button[data-tab="${id}"]`).classList.add('active')}
function renderChecks(){$('#playerChecks').innerHTML=playersSorted().map(p=>`<label class="player-check"><input type="checkbox" data-id="${esc(p.id)}" ${state.selected.includes(p.id)?'checked':''}><span>${esc(nm(p))}</span></label>`).join('');$('#selectedCount').textContent=state.selected.length;$('#status').textContent=`Version ${VERSION} • ${state.players.length} players`;renderRosterMeta()}
function formatDate(ms,detail=false){if(!ms)return '';const d=new Date(ms);return detail?d.toLocaleString():d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function renderRosterMeta(){const m=state.rosterMeta,short=m?`Roster: ${formatDate(m.fileModified,false)}${m.localEdited?' • locally edited':''}`:'Roster: Existing local data';$('#rosterStamp').textContent=short;const detail=m?`Current roster: ${esc(m.fileName)}<br>Modified: ${formatDate(m.fileModified,true)}<br>Imported: ${formatDate(m.importedAt,true)}${m.localEdited?'<br><b>Locally edited after import</b>':''}`:'Current roster: Existing local data';$('#rosterImportDetail').innerHTML=detail}
function renderTags(){if(!$('#tagInputs').children.length)$('#tagInputs').innerHTML=TAGS.map(t=>`<label class="chip"><input type="checkbox" value="${t}">${t}</label>`).join('');if(!$('#filterTags').children.length)$('#filterTags').innerHTML=TAGS.map(t=>`<label class="chip"><input type="checkbox" value="${t}">${t}</label>`).join('')}
function filteredPlayers(){const f=state.filters||{},name=(f.name||'').trim().toLowerCase(),ratings=f.ratings||[],genders=f.genders||[],tags=f.tags||[],special=f.special||[];return playersSorted().filter(p=>{if(name&&!`${p.first} ${p.last||''}`.toLowerCase().includes(name))return false;if(ratings.length&&!ratings.some(x=>x==='9'?(p.rating>=9&&p.rating<=10):p.rating>=+x&&p.rating<+x+1))return false;if(genders.length&&!genders.includes(p.gender||'blank'))return false;if(tags.length){const matches=tags.map(t=>p.tags.includes(t));if((f.tagMode||'any')==='all'?!matches.every(Boolean):!matches.some(Boolean))return false}if(special.includes('defaultRating')&&p.rating!==3)return false;if(special.includes('noTags')&&p.tags.length)return false;if(special.includes('selected')&&!state.selected.includes(p.id))return false;if(special.includes('notSelected')&&state.selected.includes(p.id))return false;return true}).sort((x,y)=>{const mode=f.sortBy||'firstAsc',first=x.first.localeCompare(y.first),last=(x.last||'').localeCompare(y.last||'');if(mode==='firstDesc')return-first;if(mode==='lastAsc')return last||first;if(mode==='lastDesc')return-(last||first);if(mode==='ratingDesc')return y.rating-x.rating||first;if(mode==='ratingAsc')return x.rating-y.rating||first;if(mode==='recent')return (y.createdAt||0)-(x.createdAt||0);return first||last})}
function renderFilterSummary(){const f=state.filters||{},count=(f.ratings?.length||0)+(f.genders?.length||0)+(f.tags?.length||0)+(f.special?.length||0)+(f.name?1:0),el=$('#activeFilters');if(!count){el.classList.add('hidden');el.textContent='';$('#filterBtn').textContent='Sort / Filter';return}el.classList.remove('hidden');el.textContent=`${count} active filter${count===1?'':'s'} • ${filteredPlayers().length} players shown`;$('#filterBtn').textContent=`Sort / Filter • ${count}`}
function renderRoster(){const list=filteredPlayers();$('#rosterList').className='player-card-grid';$('#rosterList').innerHTML=list.map(p=>`<button type="button" class="player-summary-card" data-id="${esc(p.id)}"><b>${esc(nm(p,true))}</b><span>Rating ${(+p.rating).toFixed(1)}</span></button>`).join('')||'<div class="notice full-span">No players match these filters.</div>';renderFilterSummary();renderRosterMeta()}
const player=id=>state.players.find(p=>p.id===id),avg=t=>t.length?t.reduce((s,id)=>s+player(id).rating,0)/t.length:0,avgLabel=t=>t.length?avg(t).toFixed(2):'—',hasTag=(t,x)=>t.some(id=>player(id).tags.includes(x));
function corePlayers(team){return team.filter(id=>T1.some(t=>player(id).tags.includes(t))).length}
function sizeWarning(team){if(team.length<2)return `<div class="size-warning">⚠ ${team.length} player${team.length===1?'':'s'} — add players before locking or publishing</div>`;if(team.length>5)return `<div class="size-warning">⚠ ${team.length} players — reduce to 5 before locking or publishing</div>`;return ''}
function coverage(team){const coed=team.some(id=>player(id).gender==='F'),core=corePlayers(team);return `<div class="coverage"><span class="pill ${coed?'ok':'miss'}">${coed?'✅':'❌'} Coed</span><span class="pill ${core>=2?'ok':'miss'}">${core>=2?'✅':'❌'} ${core}/2 core players</span><span class="tier-label">Tags</span>${TAGS.map(t=>`<span class="pill ${hasTag(team,t)?'ok':'miss'}">${hasTag(team,t)?'✅':'❌'} ${t}</span>`).join('')}</div>`}
function renderTeams(){$('#teamGrid').innerHTML=state.teams.map((t,i)=>`<article class="team-card ${state.locks[i]?'team-locked':''}" data-team="${i}"><h2>Team ${i+1}<small>Avg ${avgLabel(t)}</small></h2>${sizeWarning(t)}<ul class="team-roster" data-team="${i}">${t.length?t.map(id=>`<li class="team-player ${state.locks[i]?'':'draggable'} ${moveSelection&&moveSelection.pid===id?'move-selected':''}" data-player="${esc(id)}" data-team="${i}" draggable="${state.locks[i]?'false':'true'}"><span class="drag-handle">☰</span>${esc(nm(player(id)))}</li>`).join(''):'<li class="empty-team">Drop players here</li>'}</ul>${coverage(t)}<button class="lock ${state.locks[i]?'locked':''}" data-i="${i}">${state.locks[i]?'Locked':'Lock team'}</button></article>`).join('')+moveTray();if(state.teams.length){$('#teamNotice').textContent=`${state.teams.length} teams • ${state.locks.filter(Boolean).length} locked`;const ids=state.teams.flat(),ct=state.teams.length,c={F:ids.filter(id=>player(id).gender==='F').length};const parts=[`Coed qualifiers: ${c.F}/${ct}`,...TAGS.map(x=>`${x}: ${ids.filter(id=>player(id).tags.includes(x)).length}/${ct}`)];$('#availability').textContent=parts.join(' • ');$('#availability').classList.remove('hidden')}bindTeamDnD()}
function renderAll(){renderTags();renderChecks();renderRoster();renderTeams()}
function sizesFor(n,c){let o=[];for(let t=2;t<=c*2;t+=2)if(n>=2*t&&n<=5*t){let s=Array(t).fill(Math.floor(n/t));for(let i=0;i<n%t;i++)s[i]++;if(Math.min(...s)>=2&&Math.max(...s)<=5)o.push(s)}return o.sort((a,b)=>b.length-a.length)[0]||null}
const pair=(a,b)=>[a,b].sort().join('|');function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function score(teams){const powers=teams.map(t=>avg(t)-(t.length===3?+state.settings.threeAdj:0)),mean=powers.reduce((a,b)=>a+b,0)/powers.length;let s=powers.reduce((z,v)=>z+(v-mean)**2,0)*90+(Math.max(...powers)-Math.min(...powers))*35;for(const t of teams){const core=corePlayers(t);if(core===0)s+=90;else if(core===1)s+=42;if(!hasTag(t,'Passer'))s+=30;if(!hasTag(t,'Hustle'))s+=24;if(!hasTag(t,'Defender'))s+=18;if(!hasTag(t,'Setter'))s+=5;if(!hasTag(t,'Attacker'))s+=4;if(!hasTag(t,'Blocker'))s+=3}return s+Math.random()*.05}
function optimize(ids,sizes,locked=[]){let best,bs=Infinity;for(let k=0;k<7000;k++){const pool=shuffle(ids),teams=[];let p=0;for(const z of sizes){teams.push(pool.slice(p,p+z));p+=z}const v=score([...locked,...teams]);if(v<bs){bs=v;best=teams}}return best}
function createTeams(){state.settings.courts=+$('#courts').value;const s=sizesFor(state.selected.length,state.settings.courts);if(!s)return toast(`Choose a count that makes 2–${state.settings.courts*2} teams of 2–5.`);state.teams=optimize(state.selected,s);state.locks=Array(state.teams.length).fill(false);save();renderTeams();tab('teams')}
function balancedSizes(n,t){if(n<2*t||n>5*t)return null;const base=Math.floor(n/t),extra=n%t;return Array.from({length:t},(_,i)=>base+(i<extra?1:0))}
function reshuffle(){const locked=state.teams.filter((_,i)=>state.locks[i]),indexes=state.teams.map((_,i)=>i).filter(i=>!state.locks[i]);if(!indexes.length)return toast('Unlock at least one team.');const pool=indexes.flatMap(i=>state.teams[i]),sizes=balancedSizes(pool.length,indexes.length);if(!sizes)return toast(`${pool.length} remaining players cannot fill ${indexes.length} unlocked teams with 2–5 players each.`);const fresh=optimize(pool,sizes,locked);let q=0;state.teams=state.teams.map((t,i)=>state.locks[i]?t:fresh[q++]);save();renderTeams()}
let dragInfo=null,pointerDrag=null,moveSelection=null;
function movePlayer(pid,from,to){if(from===to||state.locks[from]||state.locks[to])return false;const fi=state.teams[from].indexOf(pid);if(fi<0)return false;state.teams[from].splice(fi,1);state.teams[to].push(pid);save();renderTeams();return true}
function selectMovePlayer(pid,from){if(state.locks[from])return;moveSelection={pid,from};renderTeams()}
function cancelMove(){moveSelection=null;renderTeams()}
function moveTray(){if(!moveSelection)return '';const p=player(moveSelection.pid);return `<div class="move-tray"><div><b>Move ${esc(nm(p,true))} to:</b></div><div class="move-destinations">${state.teams.map((_,i)=>`<button class="move-destination ${i===moveSelection.from||state.locks[i]?'disabled':''}" data-dest="${i}" ${i===moveSelection.from||state.locks[i]?'disabled':''}>Team ${i+1}</button>`).join('')}<button class="secondary cancel-move">Cancel</button></div></div>`}
function clearDragUI(){$$('.drag-over,.dragging').forEach(x=>x.classList.remove('drag-over','dragging'));const g=$('#dragGhost');if(g)g.remove()}
function bindTeamDnD(){$$('.team-player.draggable').forEach(el=>{el.ondragstart=e=>{dragInfo={pid:el.dataset.player,from:+el.dataset.team};e.dataTransfer.setData('text/plain',dragInfo.pid);e.dataTransfer.effectAllowed='move';el.classList.add('dragging')};el.ondragend=()=>{dragInfo=null;clearDragUI()};el.ondragover=e=>{if(dragInfo&&+el.dataset.team!==dragInfo.from){e.preventDefault();el.classList.add('drag-over')}};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();if(dragInfo)movePlayer(dragInfo.pid,dragInfo.from,+el.dataset.team);dragInfo=null;clearDragUI()};el.onpointerdown=e=>{if(e.target.closest('.drag-handle'))startPointerDrag(e,el)}});$$('.team-roster').forEach(z=>{z.ondragover=e=>{if(dragInfo&&+z.dataset.team!==dragInfo.from){e.preventDefault();z.closest('.team-card').classList.add('drag-over')}};z.ondragleave=()=>z.closest('.team-card').classList.remove('drag-over');z.ondrop=e=>{e.preventDefault();if(dragInfo)movePlayer(dragInfo.pid,dragInfo.from,+z.dataset.team);dragInfo=null;clearDragUI()}})}
function startPointerDrag(e,el){if(e.pointerType==='mouse'||state.locks[+el.dataset.team])return;const timer=setTimeout(()=>{pointerDrag={pid:el.dataset.player,from:+el.dataset.team,id:e.pointerId};el.setPointerCapture(e.pointerId);const g=document.createElement('div');g.id='dragGhost';g.className='drag-ghost';g.textContent=el.textContent.trim();document.body.append(g);positionGhost(e);el.classList.add('dragging')},280);const cancel=()=>clearTimeout(timer);el.onpointerup=cancel;el.onpointercancel=cancel;el.onpointermove=ev=>{if(!pointerDrag)return;ev.preventDefault();positionGhost(ev);$$('.drag-over').forEach(x=>x.classList.remove('drag-over'));const under=document.elementFromPoint(ev.clientX,ev.clientY),card=under&&under.closest('.team-card');if(card&&!state.locks[+card.dataset.team]&&+card.dataset.team!==pointerDrag.from)card.classList.add('drag-over')};el.onpointerup=ev=>{clearTimeout(timer);if(!pointerDrag)return;const under=document.elementFromPoint(ev.clientX,ev.clientY),target=under&&under.closest('.team-player'),card=under&&under.closest('.team-card');if(card&&!state.locks[+card.dataset.team])movePlayer(pointerDrag.pid,pointerDrag.from,+card.dataset.team);pointerDrag=null;clearDragUI()}}
function positionGhost(e){const g=$('#dragGhost');if(g){g.style.left=(e.clientX+12)+'px';g.style.top=(e.clientY+12)+'px'}}
async function hashWithPrefix(s,prefix){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(prefix+s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const hash=s=>hashWithPrefix(s,'volley-app|'),legacyHash=s=>hashWithPrefix(s,'volley|');
$$('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#playerChecks').onchange=async e=>{const id=e.target.dataset.id;if(!id)return;state.selected=e.target.checked?[...new Set([...state.selected,id])]:state.selected.filter(x=>x!==id);await save();renderChecks()};$('#selectAll').onclick=async()=>{state.selected=state.players.map(p=>p.id);await save();renderChecks()};$('#clearAll').onclick=async()=>{state.selected=[];await save();renderChecks()};$('#createTeams').onclick=createTeams;$('#reshuffle').onclick=reshuffle;$('#teamGrid').onclick=async e=>{const dest=e.target.closest('.move-destination');if(dest&&moveSelection){const {pid,from}=moveSelection;moveSelection=null;movePlayer(pid,from,+dest.dataset.dest);return}if(e.target.closest('.cancel-move'))return cancelMove();const row=e.target.closest('.team-player');if(row&&!e.target.closest('.drag-handle'))return selectMovePlayer(row.dataset.player,+row.dataset.team);const card=e.target.closest('.team-card');if(card&&moveSelection&&!e.target.closest('button')){const {pid,from}=moveSelection;moveSelection=null;movePlayer(pid,from,+card.dataset.team);return}if(!e.target.classList.contains('lock'))return;const i=+e.target.dataset.i;if(!state.locks[i]&&(state.teams[i].length<2||state.teams[i].length>5))return toast(`Team ${i+1} has ${state.teams[i].length} players. Teams must have 2–5 players before locking.`);state.locks[i]=!state.locks[i];await save();renderTeams()};
function restoreFilterControls(){const f=state.filters||{};$('#filterName').value=f.name||'';$('#sortBy').value=f.sortBy||'firstAsc';$$('#filterRatings input').forEach(x=>x.checked=(f.ratings||[]).includes(x.value));$$('#filterGender input').forEach(x=>x.checked=(f.genders||[]).includes(x.value));$$('#filterTags input').forEach(x=>x.checked=(f.tags||[]).includes(x.value));$$('#filterSpecial input').forEach(x=>x.checked=(f.special||[]).includes(x.value));$('#filterTagMode').value=f.tagMode||'any'}
let playerFormSnapshot='';function snapshotPlayerForm(){return JSON.stringify({first:$('#firstName').value,last:$('#lastName').value,rating:$('#rating').value,gender:$('#gender').value,tags:$$('#tagInputs input:checked').map(x=>x.value).sort()})}function openPlayerForm(p=null){resetForm();$('#playerFormTitle').textContent=p?'Edit Player':'Add Player';$('#removePlayer').classList.toggle('hidden',!p);if(p){$('#firstName').value=p.first;$('#lastName').value=p.last;$('#rating').value=p.rating;$('#gender').value=p.gender;$$('#tagInputs input').forEach(x=>x.checked=p.tags.includes(x.value));$('#editId').value=p.id;$('#savePlayer').textContent='Save Changes'}$('#playerForm').classList.remove('hidden');playerFormSnapshot=snapshotPlayerForm();$('#firstName').focus()}function closePlayerForm(){if(snapshotPlayerForm()!==playerFormSnapshot&&!confirm('Discard unsaved changes?'))return;resetForm();$('#playerForm').classList.add('hidden')}$('#addNewBtn').onclick=()=>openPlayerForm();$('#closePlayerForm').onclick=closePlayerForm;$('#cancelEdit').onclick=closePlayerForm;$('#filterBtn').onclick=()=>$('#filterPanel').classList.toggle('hidden');$('#closeFilters').onclick=()=>$('#filterPanel').classList.add('hidden');function captureFilters(){state.filters={name:$('#filterName').value,ratings:$$('#filterRatings input:checked').map(x=>x.value),genders:$$('#filterGender input:checked').map(x=>x.value),tags:$$('#filterTags input:checked').map(x=>x.value),tagMode:$('#filterTagMode').value,sortBy:$('#sortBy').value,special:$$('#filterSpecial input:checked').map(x=>x.value)}}$('#applyFilters').onclick=async()=>{captureFilters();await save();renderRoster();$('#filterPanel').classList.add('hidden')};$('#clearFilters').onclick=async()=>{$$('#filterPanel input').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value=''});$('#filterTagMode').value='any';state.filters={name:'',ratings:[],genders:[],tags:[],tagMode:'any',special:[],sortBy:'firstAsc'};$('#sortBy').value='firstAsc';await save();renderRoster()};
$('#removePlayer').onclick=async()=>{const id=$('#editId').value,p=player(id);if(!p||!confirm(`Remove ${nm(p,true)}?`))return;state.players=state.players.filter(x=>x.id!==id);state.selected=state.selected.filter(x=>x!==id);state.teams=state.teams.map(t=>t.filter(x=>x!==id));state.rosterMeta={...(state.rosterMeta||{}),localEdited:true};playerFormSnapshot=snapshotPlayerForm();resetForm();$('#playerForm').classList.add('hidden');await save();renderAll()};
$('#playerForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value||uid(),p={id,first:$('#firstName').value.trim(),last:$('#lastName').value.trim(),rating:+$('#rating').value,gender:$('#gender').value,tags:$$('#tagInputs input:checked').map(x=>x.value),createdAt:player(id)?.createdAt||Date.now()};if(!p.first||p.rating<1||p.rating>10)return toast('Enter a first name and rating from 1.0–10.0.');const i=state.players.findIndex(x=>x.id===id);if(i>=0)state.players[i]=p;else state.players.push(p);state.rosterMeta={...(state.rosterMeta||{}),localEdited:true};resetForm();$('#playerForm').classList.add('hidden');await save();renderAll()};
function resetForm(){$('#playerForm').reset();$('#rating').value='3.0';$('#editId').value='';$('#savePlayer').textContent='Add player';$('#cancelEdit').classList.add('hidden')}
$('#rosterList').onclick=e=>{const card=e.target.closest('.player-summary-card');if(!card)return;const p=player(card.dataset.id);if(p)openPlayerForm(p)};
$('#publish').onclick=async()=>{if(!state.teams.length)return toast('Create teams first.');const bad=state.teams.findIndex(t=>t.length<2||t.length>5);if(bad>=0)return toast(`Team ${bad+1} has ${state.teams[bad].length} players. Every team must have 2–5 players before publishing.`);$('#publishedTeams').innerHTML=state.teams.map((t,i)=>`<article class="published-card"><h2>Team ${i+1}</h2><ul>${t.map(id=>`<li>${esc(nm(player(id)))}</li>`).join('')}</ul></article>`).join('');state.history=[...(state.history||[]),{id:uid(),publishedAt:Date.now(),teams:state.teams.map(t=>t.map(id=>({id,name:nm(player(id),true)})))}].slice(-50);await save();$('#publishView').classList.remove('hidden')};$('#closePublish').onclick=()=>$('#publishView').classList.add('hidden');
$('#saveSettings').onclick=async()=>{state.settings={...state.settings,courts:+$('#courts').value,threeAdj:+$('#threeAdj').value};await save();toast('Settings saved.')};$('#setCode').onclick=async()=>{const x=$('#newCode').value;if(x.length<4)return toast('Use at least 4 characters.');state.passHash=await hash(x);await save();$('#newCode').value='';toast('Passcode set.')};$('#removeCode').onclick=async()=>{state.passHash='';await save();toast('Passcode removed.')};$('#unlockForm').onsubmit=async e=>{e.preventDefault();const code=$('#unlockCode').value,canonical=await hash(code),legacy=await legacyHash(code);if(canonical===state.passHash||legacy===state.passHash){if(legacy===state.passHash&&canonical!==state.passHash){state.passHash=canonical;await save()}$('#gate').classList.add('hidden');$('#unlockCode').value=''}else toast('Incorrect passcode.')};
function exportFileName(){const d=new Date(),pad=n=>String(n).padStart(2,'0'),stamp=`${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;return `volleyball-roster-v${VERSION}-${stamp}.json`}
$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify({...state,history:undefined,passHash:''},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=exportFileName();a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=async e=>{try{const file=e.target.files[0],d=JSON.parse(await file.text());if(!Array.isArray(d.players))throw 0;const passHash=state.passHash,history=state.history,revision=state.revision,updatedAt=state.updatedAt,embedded=d.rosterMeta||null;state={...state,...d,history,passHash,revision,updatedAt,rosterMeta:{fileName:file.name,fileModified:file.lastModified||Date.now(),importedAt:Date.now(),localEdited:false,embeddedSource:embedded},settings:{...state.settings,...d.settings}};state.players=state.players.map(p=>({...p,last:p.last||'',gender:['M','F'].includes(p.gender)?p.gender:'',tags:Array.isArray(p.tags)?p.tags:[]}));await save();renderAll();toast('Backup imported.')}catch{toast('Invalid backup.')}};

function syncVisualBottom(){if(!window.visualViewport){document.documentElement.style.setProperty('--visual-bottom','0px');return}const vv=window.visualViewport,layoutHeight=document.documentElement.clientHeight,gap=Math.max(0,layoutHeight-(vv.offsetTop+vv.height));document.documentElement.style.setProperty('--visual-bottom',gap+'px')}
if(window.visualViewport){window.visualViewport.addEventListener('resize',syncVisualBottom);window.visualViewport.addEventListener('scroll',syncVisualBottom)}
window.addEventListener('orientationchange',()=>setTimeout(syncVisualBottom,100));syncVisualBottom();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));load();